"""empty message

Revision ID: 101cbda352ff
Revises: 6c5344d6ca0a
Create Date: 2023-12-25 14:20:11.782085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '101cbda352ff'
down_revision = '6c5344d6ca0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.alter_column('invested_amount',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.alter_column('invested_amount',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
